### ISSUE TITLE
Error while creating Tables

### ISSUE THREAD

**Issue by LuLuLiLa** [sLoPPydrive/PGPool#1]
When I start the "pgpool.py" i get this error:

Traceback (most recent call last):
  File "pgpool.py", line 91, in <module>
    db = init_database(app)
  File "/home/pokemaphd/PGPool/pgpool/models.py", line 179, in init_database
    create_tables(db)
  File "/home/pokemaphd/PGPool/pgpool/models.py", line 332, in create_tables
    db.create_tables([table], safe=True)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3574, in create_tables
    create_model_tables(models, fail_silently=safe)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4940, in create_model_tables
    m.create_table(**create_table_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 4624, in create_table
    db.create_table(cls)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3571, in create_table
    return self.execute_sql(*qc.create_table(model_class, safe))
  File "/usr/local/lib/python2.7/dist-packages/playhouse/shortcuts.py", line 203, in execute_sql
    sql, params, require_commit)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3492, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3316, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3485, in execute_sql
    cursor.execute(sql, params or ())
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 161, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 317, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1021, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 120, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 115, in _check_mysql_exception
    raise InternalError(errno, errorvalue)
peewee.InternalError: (1709, u'Index column size too large. The maximum column size is 767 bytes.')

**Comment by j16sdiz** [comment]
Upgrade to MySQL 5.7/later.

**Comment by sLoPPydrive** [comment]
Doesn't have anything to do with your MySQL version. Your database was created using utf8mb4 charset which is causing trouble. I will fix that properly in a future version. In the meantime, execute the following statement:
```
ALTER DATABASE pgpool CHARACTER SET utf8 COLLATE utf8_general_ci;
```
(if your database has a different name than `pgpool`, use that instead ;-)
